# Configuración base de la aplicación.
insumos:
  directa:
    path: "Insumos/Directa/"
    universo_directa:
      nom_base: "Universo de Clientes - Directa.xlsb"
      nom_hoja: "Maestra"
      renombrar_cols: {
          "Cód. Cliente": "Cod Cliente",
          "Razon_Social": "Razón Social",
          "Nombre Cliente": "Nombre Comercial",
          "Población": "Municipio",
          "Cód. Región": "Cód. Departamento",
          "Dirección": "Dirección",
          "Distrito": "Barrio",
          "Cód. Of. Vtas": "Cód. Oficina de Ventas",
          "Función Inter.": "Función Inter.",
          "Cód. Vendedor": "Cód. Vendedor",
          "Of. de Ventas": "Oficina de Ventas",
          "Regional": "Regional",
          "Región": "Región",
          "Cód. Tipología" : "Cód. Tipología",
          "Nombre Vendedor": "Nombre Vendedor",
          "Cód. Jefe Vtas": "Cód. Jefe de Ventas",
          "Nombre Jefe Ventas": "Jefe de Ventas",
      }
      orden_prioridad_jv_vend : ["Z6", "ZA", "Z1", "Z7","Y8","Y9", "Y3", "RG"]
      cols_duplicar:
        - origen: "Cod Cliente"
          destinos: ["Cod Actual", "Cliente"]

    maestra_inactivos_dir:
      nom_base: "Maestra Inactivos Directa.xlsx"
      nom_hoja: "Clientes_Inactivos_AGCO"
      renombrar_cols: &cols_maes_indir {
        "Nºcliente": "Cod Cliente",
        "Nombre 1": "Razón Social",
        "Coment referentes di": "Nombre Comercial",
        "Cód. Población" : "Cód. Población",
        "Región": "Cód. Departamento",
        "Calle y nº": "Dirección",
        "Distrito": "Barrio",
        "Ofic venta": "Cód. Oficina de Ventas",
        "Grupo clie": "Cód. Tipología",
        "Función in": "Función Inter.",
        "Núm person": "Cód. Jefe de Ventas",
        "Nombre de pila": "Jefe de Ventas",
        "Coordenada X": "Coordenada X",
        "Coordenada Y": "Coordenada Y"
      }
      orden_prioridad_jv_vend : &orden_prioridad ["Z6", "ZA", "Z1", "Z7", "Z5", "Y9", "Y3", "RG"]
      # Diccionario donde cada clave tiene una lista de columnas: dict[str: list[str]]
      # Cada lista representa las columnas usadas en el merge.

      path_guardado : "Resultados/maestra_inactivos_directa_final.xlsx"

    base_inicio_mes_dir:
      nom_base: "Base Inicio Mes - Directa.xlsx"
      nom_hoja: "Clientes_Activos_AGCO"
      renombrar_cols:  
        <<: *cols_maes_indir
        "Población": "Municipio"
      
      # cols_duplicar: Lista donde cada elemento es un dict[str: list[str]]
      cols_duplicar:
        - origen: "Cód. Jefe de Ventas"
          destinos: ["Cód. Vendedor"]
        - origen: "Jefe de Ventas"
          destinos: ["Nombre Vendedor"]
        - origen: "Cod Cliente"
          destinos: ["Cod Actual", "Cliente"]

      orden_prioridad_jv_vend : *orden_prioridad 
          
    # Orden final de columnas para el proceso de la directa. 
    cols_finales: &cols_finales 
      - "Cod Cliente"
      - "Razón Social"
      - "Nombre Comercial"
      - "Cód. Jefe de Ventas"
      - "Jefe de Ventas"
      - "Función Inter."
      - "Cód. Vendedor"
      - "Nombre Vendedor"
      - "Canal Transformado"
      - "Subcanal Transformado"
      - "Segmento Transformado"
      - "Cód. Oficina de Ventas"
      - "Oficina de Ventas"
      - "Regional"
      - "Región"
      - "Dirección"
      - "Barrio"
      - "Municipio"
      - "Departamento"
      - "Tipo Población"
      - "Coordenadas Unificado (Y-X)"
      - "Cod Actual"
      - "Cliente"
      - "Fuente"

    path_guardado : "Resultados/universo_directa_completo.xlsx"

  indirecta:
    path: "Insumos/Indirecta/"
    universo_indirecta: 
      nom_base: "Universo de Clientes - Indirecta.xlsb"
      nom_hoja: "BD"
      renombrar_cols: 
        r_id_agente_comercial: "Cód. Jefe de Ventas"
        cv_nombre_agente_comercial: "Jefe de Ventas"
        r_id_cliente: "Cod Cliente"
        cv_nombre_completo_cliente: "Razón Social"
        cv_barrio: "Nombre Comercial"
        cv_direccion: "Dirección"
        cv_id_ciudad: "Cód. Población"
        Cod_CRM: "Cod Actual"
        Canal Trans: "Canal Transformado"
        Subcanal trans: "Subcanal Transformado"
        Segmento Trans: "Segmento Transformado"
        Region: "Región"
        Regional: "Regional"
        Cod_oficina: "Cód. Oficina de Ventas"
        Nom_oficina: "Oficina de Ventas"
        Cod_Zona: "Cód. Vendedor"
        Zona: "Nombre Vendedor"
        "barrio" : "Barrio"
    
    path_guardado : "Resultados/universo_indirecta_completo.xlsx"
    path_nulos : "Resultados/df_municipios_nulos.xlsx"
    
    dict_cols_comunes_indir_amovil_inacindir: &cols_comunes_indirecta
      COD_AC: "Cód. Jefe de Ventas"
      AGENTE_COMERCIAL: "Jefe de Ventas"
      CODIGO_ECOM: "Cod Cliente"
      NOMBRE_NEG: "Nombre Comercial"
      COD_DPTO: "Cód. Departamento"
      COD_CIUDAD: "Cód. Población"
      BARRIO: "Barrio"
      COORDENADA_X: "Coordenada X"
      COORDENADA_Y: "Coordenada Y"
      TIPOLOGIA: "Cód. Tipología"
      RAZON_SOCIAL: "Razón Social"
      DIRECCION : "Dirección"

    base_inicio_mes_indir:
      nom_base: "Base Inicio Mes - Indirecta.xlsx"
      nom_hoja: "Comercial Nutresa"
      renombrar_cols:  
        <<: *cols_comunes_indirecta
        COD_CRM: "Cod Actual"
        COD_OF_VENTAS: "Cód. Oficina de Ventas"

      dict_cn_sub_seg_null:
        "Canal Transformado" : "Otros Canales"
        "Subcanal Transformado" : "Otros Sub Canales"
        "Segmento Transformado" : "Otros Segmentos"

      dict_cols_constantes :  
        "Función Inter." : "-"
        "Cód. Vendedor": "Sin Zona"
        "Nombre Vendedor" : "Sin Zona"

    maestra_inactivos_amovil:
      nom_base: "MaestraClientesInactivos Amovil.xlsx"
      nom_hoja: "Comercial Nutresa"
      renombrar_cols: 
        "CODCRM" : "Cod Actual"
        "COD_REGION" : "Cód. Oficina de Ventas"
        <<: *cols_comunes_indirecta

    maestra_inactivos_indir:
      nom_base: "Maestra Inactivos Indirecta.xlsx"
      nom_hoja: "Comercial Nutresa"
      renombrar_cols: 
        COD_CRM : "Cod Actual"
        "COD_REGION" : "Cód. Oficina de Ventas"
        <<: *cols_comunes_indirecta
      
      path_guardado : "Resultados/maestra_inactivos_directa_final.xlsx"
      
    cols_finales : *cols_finales

  drivers:
    path: "Insumos/Drivers/"
    nom_base: "Drivers Universos.xlsx"
    nom_hojas: ["Regionales","Tipologías","Municipios","Agentes Comerciales"]
    cols:
      "Regionales":
        - "Cód. Oficina de Ventas"
        - "Oficina de Ventas"
        - "Regional"
        - "Región"
      "Tipologías":
        - "Cód. Tipología"
        - "Canal Transformado"
        - "Subcanal Transformado"
        - "Segmento Transformado"
      "Municipios":
        - "Cód. Población"
        - "Municipio"
        - "Cód. Departamento"
        - "Departamento"
        - "Tipo Población"
      "Agentes Comerciales":
        - "Cód. Jefe de Ventas"
        - "Jefe de Ventas"

dict_cols : {
    "cod_cliente": "Cod Cliente",
    "nombre_razon": "Razón Social",
    "nombre_comercial": "Nombre Comercial",
    "cod_poblacion" : "Cód. Población",
    "municipio": "Municipio",
    "cod_departamento": "Cód. Departamento",
    "direccion": "Dirección",
    "barrio": "Barrio",
    "cod_oficina": "Cód. Oficina de Ventas",
    "canal_trans": "Canal Transformado",
    "subcn_trans" : "Subcanal Transformado",
    "segm_trans" : "Segmento Transformado",
    "funcion_inter": "Función Inter.",
    "oficina_ventas": "Oficina de Ventas",
    "regional": "Regional",
    "region": "Región",
    "cod_jefe_vtas": "Cód. Jefe de Ventas",
    "nom_jefe_vtas": "Jefe de Ventas",
    "cod_vendedor": "Cód. Vendedor",
    "nom_vendedor": "Nombre Vendedor",
    "coord_x": "Coordenada X",
    "coord_y": "Coordenada Y",
    "coord_unif" : "Coordenadas Unificado (Y-X)",
    "cod_actual" : "Cod Actual",
    "cliente" : "Cliente",
    "cod_tipologia" : "Cód. Tipología",
    # Constantes no columnas. valor_nulo utilizado para rellenar nulos masivamente
    "valor_nulo" : "N/A",
    "valor_guion" : "-",
    "valor_KAM" : "KAM",
}


resultados:
  path_resultado: "Resultados\\"

